services:
  - type: web
    name: firmfoundation
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    postDeployCommand: "bundle exec rails db:migrate" 