services:
  - type: web
    name: firmfoundation
    env: ruby
    plan: free
    buildCommand: "./.render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: firmfoundation-db
          property: connectionString
      - key: REDIS_URL
        value: redis://red-d0lt9sadbo4c73c8v7ag:6379 